server:
  port: 8080

spring:
  application:
    name: authservice

  cloud:
    stream:
      bindings:
        output:
          destination: auth-user
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

auth:
  dauth:
    base-url: ${DAUTH_BASE_URL}
    client-id: ${DAUTH_CLIENT}
    client-secret: ${DAUTH_SECRET}
    redirect-url: ${DAUTH_REDIRECT}

jwt:
  secret: ${JWT_SECRET}
  exp: ${JWT_EXP}
