server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: WARN
    com.sugang.sugang: DEBUG

spring:
  application:
    name: auth-service

  cloud:
    stream:
      bindings:
        output:
          destination: ${KAFKA_TOPIC}
          content-type: application/json
      kafka:
        binder:
          zkNodes: ${KAFKA_ZOOKEEPER}
          brokers: ${KAFKA_BROKER}

auth:
  dauth:
    base-url: ${DAUTH_BASE_URL}
    client-id: ${DAUTH_CLIENT}
    client-secret: ${DAUTH_SECRET}
    redirect-url: ${DAUTH_REDIRECT}

jwt:
  secret: ${JWT_SECRET}
  exp: ${JWT_EXP}
